# Set Variable channel_name_value
- name: Set Variable channel_name_value 
  set_fact:
    channel_name_value: "{{ channel.channel_name | lower }}"
  loop: "{{ channel.orderers }}"
  loop_control:
    loop_var: ord_org
  when: ord_org == org.name
