##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role deletes the channel artifacts                              #       
#############################################################################################

# Delete BASE 64 encoded genesis blocks for all channels
- name: Delete genesis block from Vault for syschannel
  shell: |
    vault kv delete {{ item.vault.secret_path | default('secretsv2') }}/{{ network.env.type }}{{ item.name | lower }}/channel-artifacts/syschannel-genesis
    target_path={{ item.vault.secret_path | default('secretsv2') }}/{{ network.env.type }}{{ item.name | lower }}/channel-artifacts;
    for key in $(vault kv list -format=json "$target_path" | jq -r '.[]'); do
      vault kv delete "$target_path/$key";
    done 
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"
  ignore_errors: yes

# Delete genesis block to Vault
- name: "Delete genesis block to Vault for app channel"  
  shell: |
    vault kv delete {{ item.vault.secret_path | default('secretsv2') }}/{{ network.env.type }}{{ item.name | lower }}/channel-artifacts/{{ channel.channel_name | lower }}-genesis
    target_path={{ item.vault.secret_path | default('secretsv2') }}/{{ network.env.type }}{{ item.name | lower }}/channel-artifacts;
    for key in $(vault kv list -format=json "$target_path" | jq -r '.[]'); do
      vault kv delete "$target_path/$key";
    done 
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"
  loop: "{{ network['channels'] }}"
  loop_control:
    loop_var: channel
